name: stac-fastapi
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      db_service:
        image: kartoza/postgis:latest
        env:
          POSTGRES_USER: username
          POSTGRES_PASS: password
          POSTGRES_DBNAME: postgis
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          ALLOW_IP_RANGE: 0.0.0.0/0
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Lint code
        uses: pre-commit/action@v2.0.0

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run migration
        run: |
          pipenv run alembic upgrade head
        env:
          POSTGRES_USER: username
          POSTGRES_PASS: password
          POSTGRES_DBNAME: postgis
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Run test suite
        run: |
          pipenv run pytest -svvv
        env:
          ENVIRONMENT: testing
          POSTGRES_USER: username
          POSTGRES_PASS: password
          POSTGRES_DBNAME: postgis
          POSTGRES_HOST_READER: localhost
          POSTGRES_HOST_WRITER: localhost
          POSTGRES_PORT: 5432
