name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install stac_fastapi_types/
          python -m pip install stac_fastapi_extensions/
          python -m pip install stac_fastapi_api/
          python -m pip install stac_fastapi_sqlalchemy/
          python -m pip install stac_fastapi_server/
          python -m pip install -e .["docs"]

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/api/ \
            --exclude_source \
            --overwrite \
            stac_fastapi


      - name: Deploy docs
        run: mkdocs gh-deploy --force
